name: Swift CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix libssh2)/lib/pkgconfig"
          swift --version
          swift build